print("Cómo te llamas?")
usuario = input()
print("Qué tal, " + usuario)
print("Cuántos años tienes?")
edad = input()
print("En 1 año tendrás " + str(int(edad) + 1) + " años.")
print("Tu nombre tiene una longitud de " + str(len(usuario)) + " caracteres.")